base:
  # Number of processes started
  process_count: 1
  # Number of pictures generated in each process
  count_per_process: 250
  # Whether to generate voc data rate
  gen_voc: False
  gen_lsvt: False
  gen_icdar: False
  gen_coco: True

provider:
  # Select the configuration of the corpus
  text:
    - name: english
      # Corpus text path
      path: assets/corpus/word-en.txt
      # When generating text, the probability of selecting this corpus
      probability: 1.0
      # How to read the corpus (read line by line: line, read word by word: word)
      type: line
      # Generated text length interval
      len_range: (1, 32)
      
  # Candidate area generation configuration
  smooth_area:
    down_scale: 32
    anchor_ratio: (0.5 ,0.17, 0.25, .5, .7)
    anchor_scale: (2, 4, 8, 12, 16)

#    anchor_ratio: (0.5 ,0.17, 0.25, 0.5, 1.0, 1.5, 2.0)
#    anchor_scale: (4, 8, 16, 24, 32, 36, 42, 46)

  # Background image selection configuration
  bg_img:
    # Select from disk
    - type: from_dir
      # The storage path of the background image of the generated image
      dir: assets/img
      # The probability of selecting the background image on the disk as the background image
      probability: 1.0

  # Text map configuration
  text_img:
    # Text file storage path
    font_file_dir: assets/font
    # Text map output path
    text_img_output_dir: output/text_img
    # Text map json information output path
    text_img_info_output_dir: output/text_img_info
    # Font size
    font_min_size: 20
    # Maximum font size
    font_max_size: 64
    # The probability of using the specified color as the text color (as opposed to automatically picking the color)
    use_char_common_color_probability: 1.0
    # Specify the optional color list of the font (when generating the font map, the color will be selected from the following color list as the font color)
    char_common_color_list:
      - (0,0,0,255)
      # - (255,0,0,255)
    # The width of the text box
    char_border_width: 0
    # The color of the text box
    char_border_color: (255,255,0,255)
    # Automatic padding to the specified ratio of long side/short side
    auto_padding_to_ratio: 0

  # Layout configuration
  layout:
    # Path to output layout file
    out_put_dir: output
    # Texture rotation angle interval
    rotate_angle_range: (-2, 2)
    # Various layout modes and their probability of selection
    strategy_list:
      # - name: HorizontalStrategy
        # probability: 1
      - name: HorizontalFlowStrategy
        probability: 1
      # - name: RandomPasteStrategy
      #   probability: 0.4

